name: Deploy Strapi to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install --legacy-peer-deps
      working-directory: strapi-app

    - name: Build Strapi
      run: npm run build
      working-directory: strapi-app

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /srv/strapi
          git pull origin main
          cd strapi-app
          npm install --legacy-peer-deps
          npm run build
          pm2 restart strapi --update-env
